#!/bin/bash

# Update package lists
sudo apt update

# Install required packages
sudo apt install -y fontconfig openjdk-17-jre

# Download Jenkins key
sudo wget -O /usr/share/keyrings/jenkins-keyring.asc https://pkg.jenkins.io/debian/jenkins.io-2023.key

# Add Jenkins repository to package sources
echo "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian binary/" | sudo tee /etc/apt/sources.list.d/jenkins.list >/dev/null

# Update package lists again
sudo apt update

# Install Jenkins
sudo apt install -y jenkins
